# Generated by Django 3.0.4 on 2020-03-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('open_stock', models.FloatField(blank=True, null=True)),
                ('high_value', models.FloatField(blank=True, null=True)),
                ('low_value', models.FloatField(blank=True, null=True)),
                ('close_value', models.FloatField(blank=True, null=True)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('prev_close_value', models.FloatField(blank=True, null=True)),
                ('ttr_dqty_value', models.FloatField(blank=True, null=True)),
                ('ttr_dval_value', models.FloatField(blank=True, null=True)),
                ('time_stamp', models.DateField(blank=True, null=True)),
                ('total_trades', models.PositiveIntegerField(blank=True, null=True)),
                ('isin', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
